// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using WBid.WBidiPad.Model;
using WBid.WBidiPad.iOS.Utility;


namespace WBid.WBidiPad.iOS
{
	public partial class CitiesOvernightsViewController : UIViewController
	{
		public ConstraintsChangeViewController ObjChangeContraints;
		public CitiesOvernightsViewController (IntPtr handle) : base (handle)
		{
		}

		public OvernightCitiesCx data;
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			SetupUI ();
			collectionView.RegisterNibForCell (CityCell.Nib, CityCell.Key);
			collectionView.Source = new CitiesOvernightSource (data);
		}

		void SetupUI ()
		{
			Title = "Overnight Cities";
			UIHelpers.StyleForButtons (new UIButton[]{btnClear, btnDone});
		}

		partial void OnClearEvent (Foundation.NSObject sender)
		{
			if (data != null) {
				if (data.No != null) {
					data.No.Clear();
				}
				if (data.Yes != null) {
					data.Yes.Clear();
				}
			}

			collectionView.Source = new CitiesOvernightSource (data);	
			collectionView.ReloadData();
		}
		public override void ViewWillDisappear (bool animated)
		{
			base.ViewWillDisappear (animated);



			//foreach (UIView view in this.View.Subviews) {

			//	DisposeClass.DisposeEx(view);
			//}
			//this.View.Dispose ();
		

		}

		partial void OnDoneEvent (Foundation.NSObject sender)
		{ 
			if ((data.No == null || data.No.Count == 0) && (data.Yes == null || data.Yes.Count == 0))
			{
				SharedObject.Instance.ListConstraint.Remove(data);
			}
			
			ObjChangeContraints.ViewDismissViewControllerfromOvernightCities(this);
			//PopViewController(null, true);
		}
	}
}
