// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace WBid.WBidiPad.iOS
{
	public partial class SortViewController : UIViewController
	{
		public SortViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
