// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TestTablewViewLeak.ViewControllers.Line
{
	public partial class CitiesPickerVC : UIViewController
	{
		public CitiesPickerVC (IntPtr handle) : base (handle)
		{
		}
	}
}
