// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TestTablewViewLeak.ViewControllers.Line
{
	public partial class SubSortViewController : UIViewController
	{
		public SubSortViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
