// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TestTablewViewLeak.ViewControllers.Line.SummaryView
{
	public partial class ModernContainerViewController : UITableViewController
	{
		public ModernContainerViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
